# Generated by Django 4.2 on 2023-04-29 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usedproduct', '0002_category_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='url',
            field=models.URLField(default='https://example.com/image.jpg'),
            preserve_default=False,
        ),
    ]
