# Generated by Django 4.0.6 on 2022-07-30 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_location_product_price_alter_product_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='src',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='url',
            field=models.URLField(max_length=1024),
        ),
    ]
