# Generated by Django 4.0.7 on 2022-08-14 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_src_alter_product_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='location',
        ),
        migrations.AddField(
            model_name='product',
            name='market',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
